### ISSUE TITLE
Error when creating templates

### ISSUE THREAD

**Issue by MaxLeedham** [tandemdude/filament#2]
If you run `python -m lightbulb.ext.filament -n` like stated in the docs, you will get the error:
```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/book/Projects/Bots/Discord/BookBot/.venv/lib/python3.10/site-packages/lightbulb/ext/filament/__main__.py", line 42, in <module>
    _t.run(args)
  File "/home/book/Projects/Bots/Discord/BookBot/.venv/lib/python3.10/site-packages/lightbulb/ext/filament/_t/__init__.py", line 57, in run
    deploy.run(f"{args.style}_bot", f"{args.style}_bot", False, True)
  File "/home/book/Projects/Bots/Discord/BookBot/.venv/lib/python3.10/site-packages/nusex/cli/commands/deploy.py", line 52, in run
    raise DoesNotExist("No template with that name exists")
nusex.errors.DoesNotExist: No template with that name exists
```

To recreate, install filament and try running `python -m lightbulb.ext.filament -n`

**Comment by tandemdude** [comment]
Fixed on master branch
